name: WildGuard Enhanced Global Conservation Scanner

on:
  schedule:
    # Run every 4 hours for maximum global coverage
    - cron: "0 */4 * * *"
  workflow_dispatch: # Manual triggers

jobs:
  enhanced-global-conservation-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 240 # 4 hours maximum

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.production.txt
          playwright install chromium
          playwright install-deps

      - name: Run Enhanced Global Scanner
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          EBAY_APP_ID: ${{ secrets.EBAY_APP_ID }}
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          EBAY_DEV_ID: ${{ secrets.EBAY_DEV_ID }}
        run: |
          echo "🌍 Starting 4-hour ENHANCED global conservation scanning..."
          echo "📊 10 Platforms: eBay, Craigslist, OLX, Marktplaats, MercadoLibre,"
          echo "   Facebook Marketplace, Alibaba, Gumtree, Avito, Bonanza"
          echo "🚫 Duplicate Prevention: Active"
          echo "🎯 1000+ endangered species keywords"
          timeout 14000s python enhanced_continuous_scanner.py || echo "✅ 4-hour enhanced scan session completed"

      - name: Run Fast Duplicate Cleanup
        if: always()
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "🧹 Running post-scan duplicate cleanup..."
          python cleanup/fast_cleanup.py || echo "✅ Cleanup completed"

      - name: Upload scan logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: enhanced-scan-logs-${{ github.run_number }}
          path: |
            *.log
            /tmp/wildguard_url_cache.json
          retention-days: 7

      - name: Enhanced Conservation Impact Report
        if: always()
        run: |
          echo "🌍 ENHANCED GLOBAL CONSERVATION SCANNING COMPLETED"
          echo "================================================="
          echo "Session duration: 4 hours maximum"
          echo "Next session: In 4 hours"
          echo "Global platforms: 10 major marketplaces"
          echo "Coverage areas: North America, Europe, Asia, Latin America"
          echo "Keywords rotated: 1000+ endangered species"
          echo "Duplicate prevention: Database + cache-based"
          echo "Focus: Global wildlife trafficking detection"
          echo "New platforms: Facebook, Alibaba, Gumtree, Avito, Bonanza"
          echo "================================================="
